// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_CRbRALHlADo9BwBS3rylO0-SLdkg4YQ',
    appId: '1:165018782658:web:1b4f0d2569200a93b2645b',
    messagingSenderId: '165018782658',
    projectId: 'project-52db0',
    authDomain: 'project-52db0.firebaseapp.com',
    storageBucket: 'project-52db0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDqcaImsPWVEHYsIj2kAr6TDnPgIBL0E',
    appId: '1:165018782658:android:b217199f8c38f979b2645b',
    messagingSenderId: '165018782658',
    projectId: 'project-52db0',
    storageBucket: 'project-52db0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6w1czTHkLwhZBra3tuD1uiI-tQqoNXQ',
    appId: '1:165018782658:ios:3958cbe685794301b2645b',
    messagingSenderId: '165018782658',
    projectId: 'project-52db0',
    storageBucket: 'project-52db0.appspot.com',
    iosBundleId: 'com.example.swagkicks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF6w1czTHkLwhZBra3tuD1uiI-tQqoNXQ',
    appId: '1:165018782658:ios:bca9c951e9627564b2645b',
    messagingSenderId: '165018782658',
    projectId: 'project-52db0',
    storageBucket: 'project-52db0.appspot.com',
    iosBundleId: 'com.example.swagkicks.RunnerTests',
  );
}
